from captions import fetcher, tagger, utils, grader

if __name__ == "__main__":
    video_id = "7J5aS_pcBj4"  # V-tubers screaming
    # video_id = "eYe2ykgxzD8"  # News clip with autogenerated subs
    result = fetcher.get_captions(video_id)
    if not result:
        print("No Japanese captions found.")
        exit()

    print(
        f"Found {'auto-generated' if result.auto_generated else 'manual'} "
        f"{'translated' if result.translated else 'original'} captions"
    )
    print("Running tagger")
    analysis = tagger.analyze_subtitles(result)
    # utils.print_analysis(analysis)
    grader.check_joyo(analysis)
