from captions import fetcher, tagger, utils

if __name__ == "__main__":
    # This video is mostly vtubers yelling
    # ...but it's manually subbed at least
    # video_id = "7J5aS_pcBj4"
    video_id = "eYe2ykgxzD8"  # News clip with autogenerated subs
    result = fetcher.get_captions(video_id)
    if not result:
        print("No Japanese captions found.")
        exit()

    print(
        f"Found {'auto-generated' if result.auto_generated else 'manual'} "
        f"{'translated' if result.translated else 'original'} captions"
    )
    print("Running tagger")
    analysis = tagger.analyze_subtitles(result)
    utils.print_analysis(analysis)
