from captions import fetcher, tagger, utils, grader

if __name__ == "__main__":
    # video_id = "7J5aS_pcBj4"  # V-tubers screaming
    # video_id = "eYe2ykgxzD8"  # News clip with autogenerated subs
    video_id = "Bd-bNehn9D4"
    result = fetcher.get_captions(video_id)
    if not result:
        print("No Japanese captions found.")
        exit()

    print(f"Found {'auto-generated' if result.auto_generated else 'manual'} captions")
    print("Running tagger")
    analysis = tagger.analyze_subtitles(result)
    grader.check_joyo(analysis)
    utils.print_analysis(analysis, 3)
