[project]
name = "imm-cap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ftfy>=6.3.1",
    "fugashi[unidic-lite]>=1.4.0",
    "youtube-transcript-api>=0.6.3",
    "yt-dlp>=2024.12.6",
]
